[package]
name = "mtvsetup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
byte-unit = "4.0.18"
filesize = "0.2.0"
glob = "0.3.1"
image = "0.24.5"
json = "0.12.4"
md-5 = "0.10.5"
walkdir = "2.3.2"
flate2 = "1.0.25"
serde = "1.0.153"
dotenv = "0.15.0"
libusb = "0.3.0"


[dependencies.mongodb]
version = "2.4.0"
features = ["tokio-sync"]
