version: "3.3"

services:
  mtv:
    image: mtv:0.0.2
    build: .
    networks:
      - mtv
    ports:
      - 8080:8080
    volumes:
      - mtv_usb1_vol:/root/usb1/
      - mtv_usb2_vol:/root/usb2/
      - mtv_usb3_vol:/root/usb3/
      - mtv_usb4_vol:/root/usb4/

networks:
  mtv:

volumes:
  mtv_usb1_vol:
    driver: local
    driver_opts:
      type: none
      device: ${MTV_USB1}
      o: bind
  mtv_usb2_vol:
    driver: local
    driver_opts:
      type: none
      device: ${MTV_USB2}
      o: bind
  mtv_usb3_vol:
    driver: local
    driver_opts:
      type: none
      device: ${MTV_USB3}
      o: bind
  mtv_usb4_vol:
    driver: local
    driver_opts:
      type: none
      device: ${MTV_USB4}
      o: bind
