version: "3.3"

services:
  db:
    # image: andresvidal/rpi3-mongodb3
    image: mongo:4.4.0
    networks:
      - mtv
    ports:
      - 27017:27017

  mtv:
    image: mtv:0.0.9
    build: .
    environment:
###### DO NOT CHANGE ANYTHNING IN THIS SECTION #################
      - MTV_MONGODB_ADDRESS=mongodb://db:27017/mtv
      - MTV_MEDIA_PATH=/root/fsData

      - MTV_MUSIC_PATH=/root/fsData/music
      - MTV_MUSIC_THUMBNAIL_PATH=/root/fsData/thumbnails
      - MTV_MUSIC_METADATA_PATH=/root/fsData/metadata

      - MTV_MOVIES_PATH=/root/fsDataMov/movies
      - MTV_MOVIES_METADATA_PATH=/root/fsDataMov/metadata
      - MTV_MOVIES_POSTERS_PATH=/root/fsDataMov/posters
      - MTV_MOVIES_THUMBNAIL_PATH=/root/fsDataMov/thumbnails

      - MTV_TVSHOWS_PATH=/root/fsDataTVShows/tvshow
      - MTV_TVSHOWS_METADATA_PATH=/root/fsDataTVShows/metadata
      - MTV_TVSHOWS_POSTERS_PATH=/root/fsDataTVShows/posters
      - MTV_TVSHOWS_THUMBNAIL_PATH=/root/fsDataTVShows/metadata

      - MTV_STATIC_PATH=/root/static
      - MTV_DOCKER_VAR=DOCKER
###### MAKE CHANGES BELOW AS NEEDED ##########################
      - MTV_SERVER_ADDRESS=http://192.168.0.94
      - MTV_SERVER_PORT=8888
      - MTV_OFFSET=25 # number of songs per page.

    networks:
      - mtv
    ports:
      - 8888:8888
    volumes:
      - mtv_music_vol:/root/fsData/
      - mtv_mov_vol:/root/fsDataMov
      - mtv_tv_vol:/root/fsDataTVShows
      - mtv_static_vol:/root/static/
      # - mtvlogvol:/root/logs/
    depends_on:
      - db

networks:
  mtv:

volumes:
  mtv_music_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/pipi/Music/
      o: bind

  mtv_mov_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/pipi/Videos/Movies
      o: bind

  mtv_tv_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/pipi/Videos/TVShows
      o: bind

  mtv_static_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/pipi/static
      o: bind
