# config for charliepi
# MTV_MEDIA_PATH: "/media/charliepi/FOO/media"
# MTV_MUSIC_PATH: "/media/charliepi/FOO/media/music/"
# MTV_MUSIC_THUMBNAIL_PATH: "/media/charliepi/FOO/media/music_thumbnails"
# MTV_MUSIC_METADATA_PATH: "/media/charliepi/FOO/media/metadata_music"
# MTV_MOVIES_PATH: "/media/charliepi/FOO/media/movies"
# MTV_MOVIES_THUMBNAIL_PATH: "/media/charliepi/FOO/media/movies_thumbnails"
# MTV_MOVIES_METADATA_PATH: "/media/charliepi/FOO/media/metadata_movies"
# MTV_OFFSET: "25"
# MTV_SERVER_PORT: "8888"
# MTV_SERVER_ADDRESS: "http://192.168.0.94"
# MTV_DOCKER_VAR: "NONE"


# config for pipi
# MTV_MONGODB_ADDRESS: "mongodb://db:27017/mtv"

MTV_MEDIA_PATH: "/home/pipi/Music/"
MTV_MUSIC_PATH: "/home/pipi/Music/music/"
MTV_MUSIC_THUMBNAIL_PATH: "/home/pipi/Music/thumbnails"
MTV_MUSIC_METADATA_PATH: "/home/pipi/Music/metadata"
MTV_MOVIES_PATH: "/home/pipi/Video/"
MTV_MOVIES_THUMBNAIL_PATH: "/home/pipi/Video/thumbnails"
MTV_MOVIES_METADATA_PATH: "/home/pipi/Video/metadata"
MTV_OFFSET: "25"

MTV_SERVER_PORT: "8888"
MTV_SERVER_ADDRESS: "http://192.168.0.94"
MTV_DOCKER_VAR: "NONE"