#############################################################
#############################################################
#############################################################
# config for charliepi
# MTV_MONGODB_ADDRESS: "mongodb://db:27017/mtv"

# MTV_MEDIA_PATH: "/media/charliepi/FOO/media"

# MTV_MUSIC_PATH: "/media/charliepi/FOO/media/Music/"
# MTV_MUSIC_THUMBNAIL_PATH: "/media/charliepi/FOO/media/Thumbnails/music"
# MTV_MUSIC_METADATA_PATH: "/media/charliepi/FOO/media/Meta/music"

# MTV_MOVIES_PATH: "/media/charliepi/FOO/media/Movies"
# MTV_MOVIES_METADATA_PATH: "/media/charliepi/FOO/media/Meta/movie"
# MTV_MOVIES_POSTERS_PATH: "/media/charliepi/FOO/media/Posters2"
# MTV_MOVIES_THUMBNAIL_PATH: "/media/charliepi/FOO/media/Thumbnails/movie"

# MTV_TVSHOWS_PATH: "/media/charliepi/FOO/media/TVShows"
# MTV_TVSHOWS_METADATA_PATH: "/media/charliepi/FOO/media/Meta/tvshows"
# MTV_TVSHOWS_POSTERS_PATH: "/media/charliepi/FOO/media/TVPosters"
# MTV_TVSHOWS_THUMBNAIL_PATH: "/media/charliepi/FOO/media/TVThumbnails"

# MTV_GZIP_PATH: /media/charliepi/FOO/media/gzip
# MTV_STATIC_PATH: "/media/charliepi/FOO/media/static"
# MTV_SERVER_ADDRESS: "http://192.168.0.94"
# MTV_SERVER_PORT: "8888"
# MTV_DOCKER_VAR: "NONE"
# MTV_OFFSET: "25"

#############################################################
#############################################################
#############################################################
MTV_MONGODB_ADDRESS: "mongodb://db:27017/mtv"

MTV_MEDIA_PATH: "/media/pi/FOO/media"

MTV_MUSIC_PATH: "/media/pi/FOO/media/Music/"
MTV_MUSIC_THUMBNAIL_PATH: "/media/pi/FOO/media/Thumbnails/music"
MTV_MUSIC_METADATA_PATH: "/media/pi/FOO/media/Meta/music"

MTV_MOVIES_PATH: "/media/pi/FOO/media/Movies"
MTV_MOVIES_METADATA_PATH: "/media/pi/FOO/media/Meta/movie"
MTV_MOVIES_POSTERS_PATH: "/media/pi/FOO/media/Posters2"
MTV_MOVIES_THUMBNAIL_PATH: "/media/pi/FOO/media/Thumbnails/movie"

MTV_TVSHOWS_PATH: "/media/pi/FOO/media/TVShows"
MTV_TVSHOWS_METADATA_PATH: "/media/pi/FOO/media/Meta/tvshows"
MTV_TVSHOWS_POSTERS_PATH: "/media/pi/FOO/media/TVPosters"
MTV_TVSHOWS_THUMBNAIL_PATH: "/media/pi/FOO/media/TVThumbnails"

MTV_GZIP_PATH: /media/pi/FOO/media/gzip
MTV_STATIC_PATH: "/media/pi/FOO/media/static"
MTV_SERVER_ADDRESS: "http://192.168.0.61"
MTV_SERVER_PORT: "8888"
MTV_DOCKER_VAR: "NONE"
MTV_OFFSET: "25"